### ISSUE TITLE
Not working html comm

### ISSUE THREAD

**Issue by mxshdev** [Stephn-R/atom-section-comments-snippets#2]
Not working html comm

**Comment by mxshdev** [comment]
Why?

**Comment by stephnr** [comment]
Can you explain how you confirmed this? Is the file your editing using the HTML syntax?

**Comment by mxshdev** [comment]
Oops. This file use php syntax. Maybe something you can include with any syntax.

**Comment by mxshdev** [comment]
Please, add snippets for any syntax.

**Comment by mxshdev** [comment]
Please, add in php syntax this comments.

**Comment by stephnr** [comment]
Fixed with latest request. See [Tag 2.4.1](https://github.com/Stephn-R/atom-section-comments-snippets/releases/tag/2.1.1)
